#ifndef WIELOSKALOWE_NEIGHBOURHOOD_H
#define WIELOSKALOWE_NEIGHBOURHOOD_H

enum Neighbourhood {
    VON_NEUMNANN,
    MOORE,
    RADIUS,
    PENTAGONAL_TOP,
    PENTAGONAL_RIGHT,
    PENTAGONAL_BOTTOM,
    PENTAGONAL_LEFT,
    PENTAGONAL_RANDOM,
    HEXAGONAL_LEFT_TOP,
    HEXAGONAL_RIGHT_TOP,
    HEXAGONAL_RANDOM,
};

const Neighbourhood PENTAGONALS[] = {Neighbourhood::PENTAGONAL_TOP, Neighbourhood::PENTAGONAL_RIGHT, Neighbourhood::PENTAGONAL_BOTTOM, Neighbourhood::PENTAGONAL_LEFT};
const Neighbourhood HEXAGONALS[] = {Neighbourhood::HEXAGONAL_LEFT_TOP, Neighbourhood::HEXAGONAL_RIGHT_TOP};

#endif //WIELOSKALOWE_NEIGHBOURHOOD_H
